name: Refresh
on:
  schedule:
    - cron: "44 10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3.1.0
        with:
          persist-credentials: false
          filter: "blob:limit=1m"
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: daily-downloads
          path: ./target/release/daily-downloads

  refresh:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3.1.0
        with:
          persist-credentials: true
      - uses: actions/download-artifact@v4
        with:
          name: daily-downloads
          path: ./target/release
      - run: ./target/release/daily-downloads download
      - run: ./target/release/daily-downloads top
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add dates
          git commit -m "Refresh"
          git push
